### ISSUE TITLE
SOCtopus pivot to thehive from Kibana gives Internal Server Error when using Strelka logs

### ISSUE THREAD

**Issue by jertel** [Security-Onion-Solutions/securityonion#1218]
Strelka logs don't have message fields which causes this error:

```
[root@jertel-mgr-iso ~]# docker logs so-soctopus
[2020-08-19 15:48:54 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-08-19 15:48:54 +0000] [1] [INFO] Listening at: http://0.0.0.0:7000 (1)
[2020-08-19 15:48:54 +0000] [1] [INFO] Using worker: sync
[2020-08-19 15:48:54 +0000] [7] [INFO] Booting worker with pid: 7
[2020-08-19 16:06:31 +0000] [1] [INFO] Handling signal: term
[2020-08-19 16:06:31 +0000] [7] [INFO] Worker exiting (pid: 7)
[2020-08-19 16:06:32 +0000] [1] [INFO] Shutting down: Master
[2020-08-19 16:09:36 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-08-19 16:09:36 +0000] [1] [INFO] Listening at: http://0.0.0.0:7000 (1)
[2020-08-19 16:09:36 +0000] [1] [INFO] Using worker: sync
[2020-08-19 16:09:36 +0000] [7] [INFO] Booting worker with pid: 7
[2020-08-19 19:32:43,541] ERROR in app: Exception on /thehive/alert/fuM0CHQBaPplp75eIbm7 [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/SOCtopus/SOCtopus.py", line 34, in createHive
    return createHiveAlert(esid)
  File "/SOCtopus/destinations.py", line 45, in createHiveAlert
    message = result['message']
KeyError: 'message'
```

**Comment by weslambert** [comment]
This is because there is no `message` field.  We remove it because it can be very large.  We should find an alternate field/fields to leverage, or put the message field back (not recommended unless we absolutely have to do so).
