### ISSUE TITLE
Issue: Securityonion 2.2(RC3) *:logstash-beats-* Could not locate that index-pattern-field (id: @timestamp)

### ISSUE THREAD

**Issue by faisalusuf** [Security-Onion-Solutions/securityonion#1493]
After doing a "Refresh Field List" is now resulting in error when trying to access Kibana --> Discover -- *:logstash-beats-*

![SO2 2-RC3-error](https://user-images.githubusercontent.com/2043079/95551006-57512180-0a23-11eb-9a8b-8533a5ed02ae.png)

Error Details:

```
Error loading data
Could not locate that index-pattern-field (id: @timestamp)
Error: Could not locate that index-pattern-field (id: @timestamp)
    at FieldParamType._this.deserialize (https://192.168.5.200/kibana/33813/bundles/plugin/data/data.plugin.js:9:345265)
    at https://192.168.5.200/kibana/33813/bundles/plugin/data/data.plugin.js:9:362647
    at Array.forEach (<anonymous>)
    at AggConfig.setParams (https://192.168.5.200/kibana/33813/bundles/plugin/data/data.plugin.js:9:362156)
    at AggConfig.set (https://192.168.5.200/kibana/33813/bundles/plugin/data/data.plugin.js:9:368734)
    at AggConfig.setType (https://192.168.5.200/kibana/33813/bundles/plugin/data/data.plugin.js:9:368155)
    at new AggConfig (https://192.168.5.200/kibana/33813/bundles/plugin/data/data.plugin.js:9:361885)
    at AggConfigs.createAggConfig (https://192.168.5.200/kibana/33813/bundles/plugin/data/data.plugin.js:9:375134)
    at https://192.168.5.200/kibana/33813/bundles/plugin/data/data.plugin.js:9:375555
    at Array.forEach (<anonymous>)
```

Thanks
Faisal.

**Comment by dougburks** [comment]
It looks like you've posted the same issue on reddit:
https://www.reddit.com/r/securityonion/comments/j7tx8r/securityonion_22_rc3_kibana_index_pattern_error/

Closing this issue.

**Comment by faisalusuf** [comment]
Yes, which one is the correct way to open the case reddit or github?

**Comment by dougburks** [comment]
reddit
