### ISSUE TITLE
SO 2.3 so-cortex error

### ISSUE THREAD

**Issue by fl66** [Security-Onion-Solutions/securityonion#1559]
Thanks for the help!

managersearch node + sensor node

# docker logs so-cortex
[warn] application - application.conf @ file:/opt/cortex/conf/application.conf: 114: analyzer.path is deprecated, use analyzer.urls instead
[warn] o.t.c.s.JobRunnerSrv - The package cortexutils for python hasn't been found
[warn] o.t.c.s.JobRunnerSrv - The package cortexutils for python hasn't been found
[warn] o.t.c.s.JobRunnerSrv - The package cortexutils for python2 hasn't been found
[warn] o.t.c.s.JobRunnerSrv - The package cortexutils for python2 hasn't been found
[info] play.api.Play - Application started (Prod)
[error] o.e.d.DBConfiguration - ElasticSearch request failure: POST:/cortex_4/_search?scroll=60000ms
StringEntity({"version":"true","query":{"bool":{"must":[{"term":{"relations":{"value":"worker"}}},{"match_all":{}}]}},"from":0,"sort":[{"_id":{"order":"desc"}}]},Some(application/json))
 => ElasticError(index_not_found_exception,no such index,Some(_na_),Some(cortex_4),None,List(ElasticError(index_not_found_exception,no such index,Some(_na_),Some(cortex_4),None,null,None)),None)
[error] o.e.d.DBConfiguration - ElasticSearch request failure: POST:/cortex_4/_search?scroll=60000ms
StringEntity({"version":"true","query":{"bool":{"must":[{"term":{"relations":{"value":"job"}}},{"term":{"status":{"value":"Waiting"}}}]}},"from":0,"sort":[{"_id":{"order":"desc"}}]},Some(application/json))
 => ElasticError(index_not_found_exception,no such index,Some(_na_),Some(cortex_4),None,List(ElasticError(index_not_found_exception,no such index,Some(_na_),Some(cortex_4),None,null,None)),None)
[warn] o.e.d.SearchWithScroll - Search error
org.elastic4play.IndexNotFoundException$: null
    at org.elastic4play.IndexNotFoundException$.<clinit>(Errors.scala)
    at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:145)
    at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
    at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
[warn] o.e.d.SearchWithScroll - Search error
org.elastic4play.IndexNotFoundException$: null
    at org.elastic4play.IndexNotFoundException$.<clinit>(Errors.scala)
    at org.elastic4play.database.DBConfiguration.$anonfun$execute$2(DBConfiguration.scala:145)
    at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
    at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
[info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:9001
[warn] o.e.c.RestClient - request [PUT http://172.31.1.254:9400/cortex_4] returned 1 warnings: [299 Elasticsearch-6.8.7-c63e621 "[types removal] The parameter include_type_name should be explicitly specified in create index requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions."]
migrateEntity(data) has finished : Success(())
migrateEntity(organization) has finished : Success(())
migrateEntity(audit) has finished : Success(())
migrateEntity(artifact) has finished : Success(())
migrateEntity(sequence) has finished : Success(())
migrateEntity(report) has finished : Success(())
migrateEntity(user) has finished : Success(())
migrateEntity(dblist) has finished : Success(())
migrateEntity(worker) has finished : Success(())
migrateEntity(job) has finished : Success(())
migrateEntity(workerConfig) has finished : Success(())
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).
This application is already running (Or delete /opt/cortex/RUNNING_PID file).

**Comment by fl66** [comment]
Posted by mistake and moved the issue to discussion. So close this one.
