### ISSUE TITLE
so-firewall addhostgroup fails

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#1590]
```
[root@jppGAmanager1 ~]# so-firewall addhostgroup syslogtosensorone
Traceback (most recent call last):
  File "/sbin/so-firewall", line 305, in <module>
    main()
  File "/sbin/so-firewall", line 296, in main
    code = cmd(args[1:])
  File "/sbin/so-firewall", line 119, in addhostgroup
    name = args[1]
IndexError: list index out of range
```

**Comment by m0duspwnens** [comment]
https://github.com/Security-Onion-Solutions/securityonion/commit/b93709e05fcd39862a02808c01b49747efc8000e

**Comment by m0duspwnens** [comment]
related to: 

https://github.com/Security-Onion-Solutions/securityonion/pull/1556

https://github.com/Security-Onion-Solutions/securityonion/pull/1556/commits/408eddee6e098f645ee2e2515199e5e47de23683
