### ISSUE TITLE
Strelka: Remove Mmbot Scanner from Backend Config

### ISSUE THREAD

**Issue by weslambert** [Security-Onion-Solutions/securityonion#2155]
We aren't currently utilizing `ScanMbbot`, so we should remove it from the config for now.

```
2020-12-01 14:52:50 - [ERROR] root [strelka.scan_wrapper]: ScanMmbot: exception while scanning uid 6e6d84a5-1075-4f30-8b10-83f5ab117255 (see traceback below)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/strelka.py", line 148, in scan_wrapper
    self.scan(data, file, options, expire_at)
  File "/usr/local/lib/python3.6/dist-packages/strelka-0.0.0-py3.6.egg/strelka/scanners/scan_mmbot.py", line 22, in scan
    response = stub.SendVba(mmbot_pb2.Vba(vba=data.decode()))
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "DNS resolution failed"
        debug_error_string = "{"created":"@1606834370.918674590","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3941,"referenced_errors":[{"created":"@1606834370.918655295","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":262,"referenced_errors":[{"created":"@1606834370.918650302","description":"DNS resolution failed","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":370,"grpc_status":14,"referenced_errors":[{"created":"@1606834370.918614249","description":"C-ares status is not ARES_SUCCESS: Domain name not found","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":244}]}]}]}"
```

**Comment by weslambert** [comment]
https://github.com/Security-Onion-Solutions/securityonion/commit/0e8f547087edf8e839cfcea195f42485f7f0362c
