### ISSUE TITLE
FIX: Cortex: CERTatPassiveDNS fails due to missing `netbase` system package dependency

### ISSUE THREAD

**Issue by 00willo** [Security-Onion-Solutions/securityonion#5013]
Setup:
Regular CentOS 7 minimal ISO install, where I then ran the security onion setup script.

Issue:
When using the `CERTatPassiveDNS_2_0` analyzer, it reports
```
getaddrinfo(pdns.cert.at): Servname not supported for ai_socktype
Traceback (most recent call last):
  File "/Cortex-Analyzers/analyzers/CERTatPassiveDNS/certat_passivedns.py", line 38, in <module>
    CERTatPassiveDNSAnalyzer().run()
  File "/Cortex-Analyzers/analyzers/CERTatPassiveDNS/certat_passivedns.py", line 18, in run 
    self.report({'results': query(self.get_data(), int(self.limit))}) 
  File "/Cortex-Analyzers/analyzers/CERTatPassiveDNS/whois_wrapper.py", line 58, in query 
    return __process_results(__query(domain, limit)) 
  File "/Cortex-Analyzers/analyzers/CERTatPassiveDNS/whois_wrapper.py", line 17, in __query 
    s = check_output(['{}'.format(os.path.join(os.path.dirname(__file__), 'whois.sh')), '--limit {} {}'.format(limit, domain)], universal_newlines=True) 
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output 
    **kwargs).stdout 
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['/Cortex-Analyzers/analyzers/CERTatPassiveDNS/whois.sh', '--limit 100 8.8.8.8']' returned non-zero exit status 2.
```

Verify issue by testing the underlying command in the container image
```
sudo docker exec -it so-cortex bash
cortex@so-cortex:/# whois -h pdns.cert.at 8.8.8.8
getaddrinfo(pdns.cert.at): Servname not supported for ai_socktype
```

I've verified this is present in the repo currently and not just in the released container image, by rebuilding the container image from the repo on another machine and testing wtih
```
git clone https://github.com/Security-Onion-Solutions/securityonion-image.git
cd securityonion-image/so-thehive-cortex
podman build . -t so-cortex-test
podman run -it --user root --entrypoint /bin/bash so-cortex-test

root@eb4862acb97b:/# whois -h pdns.cert.at 8.8.8.8
getaddrinfo(pdns.cert.at): Servname not supported for ai_socktype
```
Resolution
```
# provides /etc/services
root@eb4862acb97b:/# apt-get install -y netbase

...  <snip apt output>

root@eb4862acb97b:/# whois -h pdns.cert.at 8.8.8.8
Timeout
# command succeeds but timeout as I'm not registered with them
```
Ref: 

- https://www.ducea.com/2006/09/11/error-servname-not-supported-for-ai_socktype/
- https://github.com/docker-library/python/issues/270

**Comment by jertel** [comment]
Closing since Cortex is no longer in the product.
