### ISSUE TITLE
Upgraded to  2.3.70  Receiving the following error

### ISSUE THREAD

**Issue by m0duspwnens** [Security-Onion-Solutions/securityonion#5268]
### Discussed in https://github.com/Security-Onion-Solutions/securityonion/discussions/5267

<div type='discussions-op-text'>

<sup>Originally posted by **lerou114** August 23, 2021</sup>
I am running a Security onion deployed as a distributed environment with a standalone fleet server and when running SOUP  upgrading 2.3.61 to 2.370 I receive this error:

[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 497, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 106, in top-level template code
  File "/usr/lib/python3.6/site-packages/jinja2/sandbox.py", line 407, in getattr
    value = getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'fleet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 261, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python3.6/site-packages/salt/utils/templates.py", line 504, in render_jinja_tmpl
    raise SaltRenderError("Jinja variable {}{}".format(exc, out), buf=tmplstr)
salt.exceptions.SaltRenderError: Jinja variable 'dict object' has no attribute 'fleet'
[CRITICAL] Rendering SLS 'base:grafana' failed: Jinja variable 'dict object' has no attribute 'fleet'
local:
    Data failed to compile:
----------
    Rendering SLS 'base:grafana' failed: Jinja variable 'dict object' has no attribute 'fleet'
</div>

**Comment by m0duspwnens** [comment]
https://github.com/Security-Onion-Solutions/securityonion/issues/5269
