### ISSUE TITLE
FIX: Error handling for `so-playbook-import`

### ISSUE THREAD

**Issue by wilson-conley** [Security-Onion-Solutions/securityonion#8554]
When attempting to import Sigma rules via `so-playbook-import`, [so-soctopus/playbook.py](https://github.com/Security-Onion-Solutions/securityonion-image/blob/c0c6956a537389745fb230f1396f41adabd6bcbe/so-soctopus/so-soctopus/playbook.py) does not properly handle Sigmac errors encountered when generating the ElastAlert config. If a Sigmac error occurs, then the `play_create` function returns the string `"Sigmac error when generating ElastAlert config"`:

https://github.com/Security-Onion-Solutions/securityonion-image/blob/c0c6956a537389745fb230f1396f41adabd6bcbe/so-soctopus/so-soctopus/playbook.py#L496-L497

However, the `play-import` function expects a dictionary to be returned and will error out when the above string is returned instead:

https://github.com/Security-Onion-Solutions/securityonion-image/blob/c0c6956a537389745fb230f1396f41adabd6bcbe/so-soctopus/so-soctopus/playbook.py#L150-L151

with error:

```
Traceback (most recent call last):                                                                                                                          
  File "<string>", line 1, in <module>                                                                                                                      
  File "/SOCtopus/playbook.py", line 151, in play_import                                                                                                    
    if creation_status['play_creation'] == 201:                                                                                                             
TypeError: string indices must be integers
```

If Sigmac errors out for one of the Sigma rule imports, `so-playbook-import` should be able to properly handle the error for that rule and continue importing the rest of the rules, even something as simple as adding this check:

https://github.com/Security-Onion-Solutions/securityonion-image/blob/c0c6956a537389745fb230f1396f41adabd6bcbe/so-soctopus/so-soctopus/playbook.py#L150-L151
```diff
        creation_status = play_create(raw, repo_sigma,"imported", "import", "import", "DRL-1.0", filen, "NA", enable_play) #changed filename added to play_create
-        if creation_status['play_creation'] == 201:
+        if not isinstance(creation_status, str) and creation_status['play_creation'] == 201:
            import_count = import_count + 1
```

I encountered this error when trying to import a Sigma rule that uses the `near` aggregation operator, which is not yet implemented in the Sigmac backend currently used. The `stderr` of the Sigmac subprocess call contains the following output:

```
An unsupported feature is required for this Sigma rule (/tmp/tmpg17mp208): None : The 'near' aggregation operator is not yet implemented for this backend   
Feel free to contribute for fun and fame, this is open source :) -> https://github.com/Neo23x0/sigma
```

However this is not captured anywhere in the `playbook.py` code:

https://github.com/Security-Onion-Solutions/securityonion-image/blob/c0c6956a537389745fb230f1396f41adabd6bcbe/so-soctopus/so-soctopus/playbook.py#L453-L455

In addition to handling the error and continuing execution as stated above, I would expect this error message from Sigmac to be displayed such that the user knows why that Sigma rule failed to import.

The exact Sigma rule I am attempting to import is:

```yaml
title: Silence.Downloader V3
id: 170901d1-de11-4de7-bccb-8fa13678d857
status: test
description: >
  Detects Silence downloader. These commands are hardcoded into the binary.
author: Alina Stepchenkova, Roman Rezvukhin, Group-IB, oscd.community
date: 2019/11/01
modified: 2021/11/27
logsource:
  category: process_creation
  product: windows
detection:
  selection_recon:
    Image|endswith:
      - '\tasklist.exe'
      - '\qwinsta.exe'
      - '\ipconfig.exe'
      - '\hostname.exe'
    CommandLine|contains: ">>"
    CommandLine|endswith: "temps.dat"
  selection_persistence:
    CommandLine|contains: '/C REG ADD "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "WinNetworkSecurity" /t REG_SZ /d'
  condition: selection_recon | near selection_persistence
fields:
  - ComputerName
  - User
  - Image
  - CommandLine
falsepositives:
  - Unknown
level: high
tags:
  - attack.persistence
  - attack.t1547.001
  - attack.discovery
  - attack.t1057
  - attack.t1082
  - attack.t1016
  - attack.t1033
  - attack.g0091

```

Full configuration:
* Security Onion v2.3.130
* I created `/opt/so/conf/soctopus/sigma-import/rule_0.yml` which contains the above Sigma rule
* I ran `sudo so-playbook-import`
* Got error:
```
Traceback (most recent call last):                                                                                                                          
  File "<string>", line 1, in <module>                                                                                                                      
  File "/SOCtopus/playbook.py", line 151, in play_import                                                                                                    
    if creation_status['play_creation'] == 201:                                                                                                             
TypeError: string indices must be integers
```

**Comment by defensivedepth** [comment]
Thanks for bringing this up, will look into it!
