### ISSUE TITLE
Source Port invalid

### ISSUE THREAD

**Issue by giveen** [Security-Onion-Solutions/securityonion#9710]
My redis is getting filled up with unprocssed logs due an invalid source port.

```
[2023-02-02T14:50:08,355][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. status: 400, action: ["index", {:_id=>nil, :_index=>"so-zeek", :routing=>nil, :pipeline=>"zeek.conn"}, {"tags"=>["beats_input_codec_plain_applied"], "dataset"=>"conn", "ecs"=>{"version"=>"8.0.0"}, "message"=>"{\"ts\":1675345796.253667,\"uid\":\"CTHZ9O3FmONKSDaPZ2\",\"id.orig_h\":\"10.100.139.59\",\"id.orig_p\":0,\"id.resp_h\":\"17.253.31.205\",\"id.resp_p\":0,\"proto\":\"tcp\",\"duration\":0.00007891654968261719,\"orig_bytes\":0,\"resp_bytes\":0,\"conn_state\":\"OTH\",\"local_orig\":true,\"local_resp\":false,\"missed_bytes\":0,\"history\":\"R\",\"orig_pkts\":3,\"orig_ip_bytes\":120,\"resp_pkts\":0,\"resp_ip_bytes\":0,\"orig_mac_oui\":\"Cisco Systems, Inc\",\"community_id\":\"1:5+b0BDShOc/McV5IQWsj7TSlPF8=\"}", "agent"=>{"ephemeral_id"=>"ead6b64d-4da5-47b8-a4dd-0ab7d1cb78a8", "type"=>"filebeat", "id"=>"d10e123e-8b19-44de-b246-9224f3601e49", "version"=>"8.5.3", "name"=>"sorfh-lxp-04"}, "@timestamp"=>2023-02-02T13:50:02.084Z, "module"=>"zeek", "type"=>"redis-input", "category"=>"network", "host"=>{"name"=>"sorfh-lxp-04"}, "log"=>{"offset"=>1023436654, "file"=>{"path"=>"/nsm/zeek/logs/current/conn.log"}}, "metadata"=>{"beat"=>"filebeat", "type"=>"_doc", "version"=>"8.5.3", "ip_address"=>"10.21.132.23"}, "@version"=>"1"}], response: {"index"=>{"_index"=>"so-zeek", "_id"=>nil, "status"=>400, "error"=>{"type"=>"illegal_argument_exception", "reason"=>"invalid source port [0]"}}}
```

```
[2023-02-02T14:50:10,149][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.13:5044, remote: 10.25.223.9:32286] Handling exception: java.net.SocketException: Connection reset (caused by: java.net.SocketException: Connection reset)
[2023-02-02T14:50:10,149][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.net.SocketException: Connection reset
        at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
        at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.65.Final.jar:4.1.65.Final]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by giveen** [comment]
@TOoSmOotH why did you close this? Its a bug as I think its not seeing zero as an integer.

**Comment by TOoSmOotH** [comment]
@giveen You already have a discussion for this.

**Comment by giveen** [comment]
> @giveen You already have a discussion for this.

That makes sense, I apologize, I just felt like this went beyond a discussion once I realize what the source of the issue. I dont believe its a misconfig on my part but an actual bug which is why I went from discussion to bug report.

**Comment by TOoSmOotH** [comment]
> > @giveen You already have a discussion for this.
> 
> That makes sense, I apologize, I just felt like this went beyond a discussion once I realize what the source of the issue. I dont believe its a misconfig on my part but an actual bug which is why I went from discussion to bug report.

Not a big deal.. normally I would just convert the issue to a discussion but since you already had one I closed it. If it is determined that it is an actual bug we will open a specific issue for the fix. We try to keep issues to things that are actionable from a code perspective.
